apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledweb-deploy
  labels:
    app: ledweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledweb
  template:
    metadata:
      labels:
        app: ledweb
    spec:
      volumes:
        - name: my-volume
          hostPath:
            path: /var/fifo
      containers:
        - name: ledweb
          image: 192.168.3.200:5000/k8sled/rpi-led:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: my-volume
              mountPath: /var/fifo
      imagePullSecrets:
        - name: registrypullsecret
