apiVersion: v1
kind: Secret
metadata:
 name: registrypullsecret
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjMuMjAwOjUwMDAiOiB7CgkJCSJhdXRoIjogImFXMWhaMlYxYzJWeU9sbDFkV1JoYVRBeE1qQT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
